### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by 3noch** [dzhus/sext#2]
I'm wondering if you knew what ["sext" meant](https://www.google.com/search?q=what+is+sexting&oq=what+is+sexting&aqs=chrome..69i57j69i60l2j69i59l2j69i60.2926j0j7&sourceid=chrome&ie=UTF-8) when you named this?

**Comment by m-renaud** [comment]
+1000 for renaming

**Comment by dzhus** [comment]
@m-renaud @3noch I'm open to your suggestions :)

**Comment by m-renaud** [comment]
https://hackage.haskell.org/package/static-text appears to be available :) It's both more descriptive and avoids the, uh, unintended bad connotation that the current name has.

**Comment by m-renaud** [comment]
You'd probably want to change the function, type, and module names in the code as well. s/sext/staticText/, s/Sext/StaticText/, s/Sextable/StaticTextable/. This would be a breaking change so you'd have to bump the major version number, this could be an opportunity to bump to version 1.0.0.0 since the names of everything changed pretty drastically.

As an aside, imho major versions of the form 0.x looks an awful lot like they're "unstable" since every other versioning scheme that I know of uses major.minor.patch. PVP allows it but I feel like it would make it more clear to newcomers that packages are stable if "stable" packages started with 1.0 as "major.major".

**Comment by dzhus** [comment]
> s/Sext/StaticText/

I tried doing this, but this means we end up with types like `StaticText 23 Text` (which just looks over descriptive) and `StaticText 32 ByteString` (which is outright confusing, «so is it Text, or ByteString, or both, or neither?»).

Renaming the associated data type to just `Static` might to be a better alternative:

```haskell
foo :: Static 32 Text
```

or even

```haskell
foo :: Static Text 32
```

which seems to read better.

This may of course clash with a bunch of other packages such as

http://hackage.haskell.org/package/distributed-static-0.3.8/docs/Control-Distributed-Static.html 
http://hackage.haskell.org/package/yesod-static-1.6.0/docs/Yesod-Static.html#v:Static

but that is still fine if you import `Data.StaticText` qualified.

**Comment by m-renaud** [comment]
Good point. One question I have is whether this package could also handle statically lengthed lists and sequences as well. If so `Static a Int` wouldn't be a bad name.

The name clashes are a good point, depending on how Static in the packages linked are used it may not be an issue, maybe see what the authors have to say (@snoyberg for yesod-static). You could also consider `StaticLength a Int` which is more verbose but avoids the name clash issue.

**Comment by m-renaud** [comment]
Duh, it says statically lengthed lists (and vectors) in the package description. In that case StaticText seems too specific anyways so Static or StaticLength seem much better.

**Comment by dzhus** [comment]
> could also handle statically lengthed lists

It already does.

**Comment by dzhus** [comment]
https://hackage.haskell.org/package/static-text

I will keep it in 0.x version range for a while longer though.
